name: Event Print

on: 
  push:
    branches:
      - main

jobs:
  
  print_workflows:
    runs-on: ubuntu-latest
    env: 
      EVENT_CONTENT: ${{ toJSON(github.event) }}
    steps:
      
      - run: |
          echo $EVENT_CONTENT

