name: kartik workflow

on: 
  # pull_request:
  #   types:
  #     - labeled

  push:
    branches:
      - main
      # - dev
  
jobs:
  my_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello"