name: kartik workflow

on: 
  # pull_request:
  #   branches:
  #     - dev

  push:
    branches:
      - main
    # branches-ignore:
    #   - dev
    #   # - dev
  
jobs:

  # Upload Artifacts
  upload_artifacts:
    runs-on: ubuntu-latest
    name: Save Output
    steps:
      - name: operations
        shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log

  my_workflow:
    runs-on: ubuntu-latest
    name: print hello 2
    steps:
      - name: print hello
        run: echo "Hello"