name: kartik workflow

on: 
  # workflow_run:
  #   workflows: [kartik]
  #   branches-ignore:
  #     - dev
  push:
    branches:
      - main4
  
jobs:

  my_workflow:
    runs-on: ubuntu-latest
    name: print hello
    steps:
      - name: print hello
        run: echo "Hello"